version: '3'
services:
  mongo-db:
    image: mongo
    ports:
      - 27017:27017
    command: mongod --bind_ip 0.0.0.0
    volumes:
      - data-mongo:/data/db
  frontend:
    build: ./frontend
    ports:
      - "80:80"
  order-service:
    build: ./order-service
    ports:
      - "8080:8080"
    depends_on:
     - mongo-db
  inventory-service:
    build: ./inventory-service
    ports:
      - "8081:8081"
    depends_on:
     - mongo-db
  shipping-service:
    build: ./shipping-service
    ports:
      - "8082:8082"
    depends_on:
     - mongo-db
volumes:
  data-mongo: