apiVersion: v1
kind: Service
metadata:
   name: kafka-broker
spec:
   selector:
     name: kafka-deployment
   type: NodePort
   ports:
   - name: kafka
     protocol: TCP
     port: 9092
     nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kafka-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      name: kafka-deployment
  template: 
    metadata: 
      labels: 
        name: kafka-deployment
    spec: 
      containers:
      - name: kafka
        image: spotify/kafka
        ports:
        - containerPort: 2181
        - containerPort: 9092
        env:
        - name: ADVERTISED_HOST
          value: "kafka-broker"
        - name: ADVERTISED_PORT
          value: "30001"  
---
apiVersion: v1
kind: Service
metadata:
   name: mongo-db
spec:
   selector:
     name: mongo-deployment
   type: NodePort
   ports:
   - name: mongo
     protocol: TCP
     port: 27017
     nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongo-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      name: mongo-deployment
  template: 
    metadata: 
      labels: 
        name: mongo-deployment
    spec: 
      containers:
      - name: mongo
        image: mongo
        command:
          - mongod
          - "--bind_ip_all"
          - "--replSet"
          - rs0
        ports:
        - containerPort: 27017